<?php
include_once("includes/session.php");
confirm_logged_in();
include_once("../includes/masterinclude.php");

$message = "";
$warning = "";
$pathName = "/images/";
$attribute_id_current = -1;
$attribute_name = "";
$updateline = ""; $deleteline = "";
$position_to_add = 0;
$name_to_add = "";
$value_to_add = "0.00";
$exclude_to_add = "N";
$scrolltobottom = "";
$spacer = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
$spacer .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
$spacer .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";

$spacer2 = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
$spacer2 .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
$spacer2 .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
$spacer2 .= "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";

if(isset($_GET['attribute_id'])){$attribute_id_current = $_GET['attribute_id'];}
if(isset($_POST['ATTRIBUTE_ID_CURRENT'])){$attribute_id_current = $_POST['ATTRIBUTE_ID_CURRENT'];}

if (isset($_POST['CREATE_ATTRIBUTE'])) {
	//create Attribute
	$fields = array("at_search_name"=>$_POST['ATTRIBUTE_SEARCH_NAME'], "at_name"=>$_POST['ATTRIBUTE_NAME'], "at_position"=>$_POST['ATTRIBUTE_POSITION']);
	$rows = Create_Attribute($fields);	
	if ($rows == 1){
		$message .= "Attribute CREATED" . "<br/>";
		$warning = "green";
		// now get autogenerated id of attribute box just created to write to options row
		$attribute = getAttributeId($_POST['ATTRIBUTE_NAME']);
		$attribute_id_current = $attribute->AT_ID;
	}else{
		$message .= "Attribute NOT CREATED!!! - PLEASE CONTACT SHOPFITTER!"; 
		$warning = "red";
	}
	$error = null;
	$error = mysql_error();
	if ($error != null) { 
		$message .= " - ERRORS FOUND ! ! ! - " . mysql_error() . " - PLEASE CONTACT SHOPFITTER!!!";
		$warning = "red";
	}
}

if (isset($_POST['UPDATE_NAME'])) {
	if(strpos($_POST['ATTRIBUTE_NAME'], "\"")){
		$message .= "Please do not use double quotes within Name field - use single quotes instead" . "<br/>";
		$warning = "red";
	}
	if(strpos($_POST['ATTRIBUTE_SEARCH_NAME'], "\"")){
		$message .= "Please do not use double quotes within Name field - use single quotes instead" . "<br/>";
		$warning = "red";
	}
	if($message == ""){
		$fields = array("at_id"=>$attribute_id_current, "at_search_name"=>$_POST['ATTRIBUTE_SEARCH_NAME'], "at_name"=>$_POST['ATTRIBUTE_NAME'], "at_position"=>$_POST['ATTRIBUTE_POSITION']);
		$rows = Rewrite_Attribute($fields);	
		if ($rows == 1){
			$message .= "Attribute Name amended successfully" . "<br/>";
			$warning = "green";
			// now get autogenerated id of attribute box just created to write to options row
			$attribute = getAttributeId($_POST['ATTRIBUTE_NAME']);
			$attribute_id_current = $attribute->AT_ID;
		}else{
			$message .= "WARNING ! ! ! - ATTRIBUTE NOT UPDATED";
			$warning = "orange";
		}
		$error = null;
		$error = mysql_error();
		if ($error != null) { 
			$message .= " - ERRORS FOUND ! ! ! - " . mysql_error() . " - PLEASE CONTACT SHOPFITTER!!!";
			$warning = "red";
		}
	}
}

if($attribute_id_current != -1){
	// get attribute box details
	$attribute = getAttribute($attribute_id_current);
	$attribute_id_current = $attribute->AT_ID;
}

//determine if an option line Update or Delete button has been hit
if(isset($_POST['VALUES_COUNTER'])){
	$updateline = 0; $deleteline = 0;
	for ($i=1; $i<=$_POST['VALUES_COUNTER']; $i++){
		if(isset($_POST['UPDATE_OPTION'.$i])){$updateline = $i; break;}
		if(isset($_POST['DELETE_OPTION'.$i])){$deleteline = $i; break;}
	}
}

if ($deleteline > 0) {
	//delete value
	$rows = Delete_Attribute_Value($attribute_id_current, $_POST['NAME_ORIGINAL'.$deleteline], "");	
	if ($rows == 1){
		$message .= "Value Line DELETED from Attribute" . "<br/>";
		$warning = "green";
	}else{
		$message .= "Value Line record NOT DELETED - PLEASE CONTACT SHOPFITTER!!!"; 
		$warning = "red";
	}
	$error = null;
	$error = mysql_error();
	if ($error != null) { 
		$message .= " - ERRORS FOUND ! ! ! - " . mysql_error() . " - PLEASE CONTACT SHOPFITTER!!!";
		$warning = "red";
	}
}

if ($updateline > 0) {
	//validate all table entries
	$message = ""; $ok = 1;
	//if(is_numeric($_POST['POSITION'.$updateline]) and $_POST['POSITION'.$updateline] > 0 and $_POST['POSITION'.$updateline] <= $_POST['VALUES_COUNTER']){$ok = 1;}else{$ok = 0;}
	if ($ok == 0){
		$message .= "Please enter a valid Line Position" . "<br/>";
		$warning = "red";
	}
	if (strlen($_POST['NAME'.$updateline]) == 0){
		$message .= "Please enter a valid Search Value" . "<br/>";
		$warning = "red";
	}
	if(strpos($_POST['NAME'.$updateline], "\"")){
		$message .= "Please do not use double quotes within the Search Value Text field - use single quotes instead" . "<br/>";
		$warning = "red";
	}
	if($message == ""){
		//loop through attribute values and rewrite each with the latest details	
		$fields = array("av_at_id"=>$attribute->AT_ID, "name_original"=>$_POST['NAME_ORIGINAL'.$updateline], "av_name"=>html_entity_decode($_POST['NAME'.$updateline], ENT_QUOTES), "av_position"=>$_POST['POSITION'.$updateline]);
		$rows = Rewrite_Attribute_Value($fields);
		if ($rows == 1){
			$message .= "{$rows} Value Line successfully UPDATED" . "<br/>";
			$warning = "green";
		}
		if (($rows == 0) and $message == "" ){
			$message .= "WARNING ! ! ! - NO VALUES UPDATED";
			$warning = "orange";
		}
		$error = null;
		$error = mysql_error();
		if ($error != null) { 
			$message .= " - ERRORS FOUND ! ! ! - " . mysql_error() . " ";
			$warning = "red";
		}
	}
}

if (isset($_POST['ADD_VALUE'])) {
	//validate fields
	$message = "";
	if (strlen($_POST['POSITION_TO_ADD']) == 0){
		$message .= "Please enter a valid Line Position" . "<br/>";
		$warning = "red";
	}
	if (strlen($_POST['NAME_TO_ADD']) == 0){
		$message .= "Please enter a valid Search Value" . "<br/>";
		$warning = "red";
	}
	if(strpos($_POST['NAME_TO_ADD'], "\"")){
		$message .= "Please do not use double quotes within the Search Value Text field - use single quotes instead" . "<br/>";
		$warning = "red";
	}
	if($message == ""){
		$fields = array("av_at_id"=>$attribute->AT_ID, "av_name"=>$_POST['NAME_TO_ADD'], "av_position"=>$_POST['POSITION_TO_ADD']);		
		$rows = Create_Attribute_value($fields);
		if ($rows == 1){
			$message = $rows . " Line ADDED to Option";
			$warning = "green";
		}
		if ($rows == 0){
			$message = "WARNING ! ! ! - NO RECORDS UPDATED!!!";
			$warning = "orange";
		}
		if ($rows > 1){
			$message = "ERROR ! ! ! - MORE THAN ONE (" . $rows . ") Line RECORD UPDATED - PLEASE CONTACT SHOPFITTER!!!";
			$warning = "red";
		}
		$error = null;
		$error = mysql_error();
		if ($error != null) { 
			$message .= " - ERRORS FOUND ! ! ! - " . mysql_error() . " - PLEASE CONTACT SHOPFITTER!!!";
			$warning = "red";
		}
	}
}

if (isset($_POST['DELETE_ATTRIBUTE'])) {
	//delete Attribute box + all associated values
	$rows = Delete_All_Attribute_values($attribute_id_current);
	if ($rows == $_POST['VALUES_COUNTER']){
		$message = $rows . " Values DELETED from Attribute<br>";
		$warning = "green";
	}else{
		$message = "ERROR ! ! ! - Only {$rows} Value Lines DELETED out of {$_POST['VALUES_COUNTER']} - PLEASE CONTACT SHOPFITTER!!!<br>";
		$warning = "red";
		
		$error = null;
		$error = mysql_error();
		if ($error != null) { 
			$message .= " - ERRORS FOUND ! ! ! - " . mysql_error() . " - PLEASE CONTACT SHOPFITTER!!!<br>";
			$warning = "red";
		}
	}
	if($warning = "green"){
		$rows = Delete_Attribute($attribute_id_current);
		if ($rows == 1){
			$message .= "Attribute successfully DELETED<br>";
			$warning = "green";
		}
		if ($rows == 0){
			$message .= "WARNING ! ! ! - Attribute NOT DELETED<br>";
			$warning = "orange";
		}
		if ($rows > 1){
			$message .= "ERROR ! ! ! - MORE THAN ONE (" . $rows . ") Attribute RECORD DELETED - PLEASE CONTACT SHOPFITTER!!!<br>";
			$warning = "red";
		}
		$error = null;
		$error = mysql_error();
		if ($error != null) { 
			$message .= " - ERRORS FOUND ! ! ! - " . mysql_error() . " - PLEASE CONTACT SHOPFITTER!!!<br>";
			$warning = "red";
		}
	}
	//initialise screen
	$attribute_id_current = -1;
	unset($attribute);
}
//if($message != ""){$scrolltobottom = "onLoad=\"scrollTo(0,2000)\" ";}

$preferences = getPreferences();
//note this will also refresh the page after amending it
$pageTitle = "Site Administration: Search Attributes";
$pageMetaDescription = $preferences->PREF_META_DESC;
$pageMetaKeywords = $preferences->PREF_META_KEYWORDS;


include_once("includes/header_admin.php");
?>
<div class="body-indexcontent_admin">
	<div class="admin">
    <br/>
	<h1>Search Tags - Create and Amend Search Tags</h1>
	<br/>
    <table align="left" border="0" cellpadding="2" cellspacing="5">
    <form name="enter-thumb" action="/_cms/amend_attributes.php" method="post">
		<!--- ATTRIBUTE BOX SELECTION ----------------------------------------------------------------------------------------------------------->
        <tr>
        	<td>Select Tag: <a href="#" class="tt"><?php echo ($preferences->PREF_TOOL_TIPS == "Y" ? "<img src=\"/_cms/csstooltips/q-icon.png\"><span class=\"tooltip\"><span class=\"top\"></span><span class=\"middle\">Create a new search tag or amend an existing one<br /><br />You must create a tag here before you can apply it for a product search</span><span class=\"bottom\"></span></span>" : "") ?></a></td>
            <td>
                <select name="ATTRIBUTE" onchange="MM_jumpMenu('parent',this,1)">
                    <option value="#">Choose from...</option>
                    <?php
					if($attribute_id_current == -1){$selected = "selected";}
					echo "<option value=\"/_cms/amend_attributes.php?attribute_id=-1\"" . $selected . ">&lt;New Option&gt;</option>";
                    $attributes = getAllAttributes();
                    foreach($attributes as $a){
						if($attribute_id_current == $a->AT_ID){
							$selected = "selected ";
						}else{
							$selected = "";
						}		
						echo "<option value=\"/_cms/amend_attributes.php?attribute_id=" . $a->AT_ID . "\" " . $selected . ">" . html_entity_decode($a->AT_NAME, ENT_QUOTES) . "</option>";
                    }
                    ?>
                </select>
			</td>
            <td></td>
        </tr>
        <tr>
        	<td>Position 
            <a href="#" class="tt"><?php echo ($preferences->PREF_TOOL_TIPS == "Y" ? "<img src=\"/_cms/csstooltips/q-icon.png\"><span class=\"tooltip\"><span class=\"top\"></span><span class=\"middle\">Lower numbers appear higher up in the list</span><span class=\"bottom\"></span></span>" : "") ?></a></td>
            <td>Name / Search Box Name</td>
        </tr>
        <tr>
        	<td>
            	<input type="text" name="ATTRIBUTE_POSITION" Size="2" value="<?php echo ($attribute_id_current == -1 ? "99" : html_entity_decode($attribute->AT_POSITION, ENT_QUOTES)) ?>" />
            </td>
            <td>
            	<input type="text" name="ATTRIBUTE_NAME" Size="50" value="<?php echo ($attribute_id_current == -1 ? "" : html_entity_decode($attribute->AT_NAME, ENT_QUOTES)) ?>" /> 
                <a href="#" class="tt"><?php echo ($preferences->PREF_TOOL_TIPS == "Y" ? "<img src=\"/_cms/csstooltips/q-icon.png\"><span class=\"tooltip\"><span class=\"top\"></span><span class=\"middle\">A unique title for the search tag; eg T-Shirts Size<br /><br />This is not seen by visitors to your website; it allows you to identify what the tag applies to</span><span class=\"bottom\"></span></span>" : "") ?></a></td>
                <input type="hidden" name="ATTRIBUTE_ID_CURRENT" Size="30" value="<?php echo htmlentities($attribute_id_current, ENT_QUOTES) ?>" />
            </td>
            <td>
            	<?php 
            	if($attribute_id_current != -1){
            		echo "<input type=\"submit\" name=\"UPDATE_NAME\" value=\"Update\" class=\"update-button\" />";
                }
                ?>
            </td>
        </tr>
        <tr>
        	<td></td>
            <td>
                <input type="text" name="ATTRIBUTE_SEARCH_NAME" Size="50" value="<?php echo ($attribute_id_current == -1 ? "" : html_entity_decode($attribute->AT_SEARCH_NAME, ENT_QUOTES)) ?>" />
                <a href="#" class="tt"><?php echo ($preferences->PREF_TOOL_TIPS == "Y" ? "<img src=\"/_cms/csstooltips/q-icon.png\"><span class=\"tooltip\"><span class=\"top\"></span><span class=\"middle\">The title to be displayed; eg Size<br /><br />This is what your site visitors see when asked to make a selection for searching</span><span class=\"bottom\"></span></span>" : "") ?></a></td>
       	</tr>
        <?php
		if($attribute_id_current == -1){
			echo "<tr>";
				echo "<td></td>";
				echo "<td>";
					echo "<input type=\"submit\" name=\"CREATE_ATTRIBUTE\" value=\"Create Tag\" class=\"create-button\">";
				echo "</td>";
				echo "<td></td>";
			echo "</tr>";
		}
		?>
        <tr>
			<td class="td-sep" colspan="3">&nbsp;</td>
		</tr>
        <?php
		if($attribute_id_current != -1){
			//--- DISPLAY OPTION LINES ---------------------------------------------------------------------------------------------------------------------------->
			echo "<tr>";
        		echo "<td>Position</td>";
           		echo "<td>Search Value</td>";
            	echo "<td></td>";
       		 echo "</tr>";
            $values = getAttributeValues($attribute);
			$cntr1 = 0; $last_position = 0;
            foreach($values as $v){
				$cntr1 ++;
                echo "<tr>";
                    echo "<td>";
						echo "<input type=\"text\" name=\"POSITION" . $cntr1 . "\" SIZE=\"2\" value=\"" . $v->AV_POSITION . "\" >";
					echo "</td>";
                    echo "<td>";
                        echo "<input type=\"text\" name=\"NAME" . $cntr1 . "\" SIZE=\"50\" value=\"" . html_entity_decode($v->AV_NAME, ENT_QUOTES) . "\" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
						echo "<input type=\"hidden\" name=\"NAME_ORIGINAL" . $cntr1 . "\" value=\"" . html_entity_decode($v->AV_NAME, ENT_QUOTES) . "\" >";
						echo "<input type=\"hidden\" name=\"ATTRIBUTE_ID" . $cntr1 . "\" value=\"" . $attribute->AT_ID . "\" >";
					echo "</td>";
					echo "<td>";
						echo "<input type=\"submit\" name=\"UPDATE_OPTION" . $cntr1 . "\" value=\"Update\" class=\"update-button\" >";
						echo "<input type=\"submit\" name=\"DELETE_OPTION" . $cntr1 . "\" value=\"Delete\" class=\"delete-button\" >";
                    echo "</td>";
                echo "</tr>";
				$last_position = $v->AV_POSITION;
            }
			echo "<tr>";
				echo "<td</td>";
				echo "<td>";
					echo "<input name=\"VALUES_COUNTER\" type=\"hidden\" value=\"" . $cntr1 . "\" />";
					//echo "<input type=\"submit\" name=\"UPDATE_OPTIONS\" value=\"Update\">";
				echo "</td>";
				echo "<td</td>";
			echo "</tr>";		
	        echo "<tr>";
                echo "<td class=\"td-sep\" colspan=\"3\"></td>";
            echo "</tr>";
			//---ADD OPTION --------------------------------------------------------------------------------------------------------------------------------------->	
			$position_to_add = $last_position + 1;
            echo "<tr>";
                echo "<td></td>";
				echo "<td>Add Search Value:</td>";
				echo "<td></td>";
            echo "</tr>";
			echo "<tr>";
                echo "<td>";
                    echo "<input type=\"text\" name=\"POSITION_TO_ADD\" SIZE=\"2\" value=\"" . $position_to_add . "\">";
				echo "</td>";
				echo "<td>";
				    echo "<input type=\"text\" name=\"NAME_TO_ADD\" SIZE=\"50\" value=\"" . $name_to_add . "\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
				echo "</td>";
				echo "<td>";
					echo "<input name=\"ID_TO_ADD\" type=\"hidden\" value=\"" . $attribute->AT_ID . "\" />";
					echo "<input name=\"ADD_VALUE\" type=\"submit\" value=\"Add\" class=\"add-button\" />";
                echo "</td>";
            echo "</tr>";             
		}
        ?>
        
        <tr>
			<td colspan="3">&nbsp;</td>
		</tr>
        <?php
		if($attribute_id_current != "" and $attribute_id_current != -1){
			echo "<tr>";
                echo "<td></td>";
				echo "<td>";
				    echo "<input type=\"submit\" name=\"DELETE_ATTRIBUTE\" value=\"Delete This Tag\"  class=\"delete-button\">";
				echo "</td>";
				echo "<td></td>";
            echo "</tr>";
		}
		?>
        <tr>
			<td colspan="3"><label class="<?php echo $warning ?>" ><?php echo $message ?></label></td>
		</tr>        

	</form>
    	<tr>
			<td colspan="3">
            	<p>To use the tag search functionality start here by creating a new tag (or edit existing tags).</p>
                <p>&nbsp;</p>
                <p>Once you've created your tags the next step is to go to the Manage Options section and add the search terms you want to assign for each option - general and/or product options.</p>
                <p>&nbsp;</p>
                <p>You can now amend your categories and select the search tags that will appear on the website pages.</p>
                <p>&nbsp;</p>
                <p>Tag searches can be used to enable website visitors to search for specific attributes on your products, for example; size or colour.</p>
                <p>&nbsp;</p>
                <p>If you assign size in one tag set and colour in a second tag set then your visitors will be able to search for predefined values such as Size: Large and Colour: Red; only items that have both those attributes in the tags will be displayed in the search results.</p>
            </td>
		</tr>
        <tr>
			<td colspan="3">&nbsp;</td>
		</tr>
    </table>
<?php
  include_once("includes/footer_admin.php");
?>

